version: '3.8'

services:
  web:
    build:
      dockerfile: ./web/Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Flask app
    environment:
      - PYTHONUNBUFFERED=1

  sockets:
    build:
      dockerfile: ./video/Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "8765:8765"  # WebSocket server
    environment:
      - PYTHONUNBUFFERED=1
