version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8765:8765"
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 app.py  # Run the web server

  sockets:
    build: .
    restart: always
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 sockets.py  # Run the sockets service
