version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Flask app
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 app.py  # Runs the Flask app

  sockets:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8765:8765"  # WebSocket server
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 sockets.py  # Runs the WebSocket server
