version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  video:
    build:
      context: .
      dockerfile: video/Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - "8765:8765"
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - web