version: '3.8'

services:
  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Add this line
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 app.py

  sockets:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8765:8765"
    environment:
      - PYTHONUNBUFFERED=1
    command: python3 sockets.py
